// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Motor.Claim.Infrastructure.Persistence.Context;

#nullable disable

namespace Motor.Claim.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260518120000_AddCoverageLimitAndEstimatePayables")]
    partial class AddCoverageLimitAndEstimatePayables
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
        }
    }
}
